// ── STATIC NEWS DATA ── generated from real WC2026 squad/context knowledge
const NEWS_DATA = {
  "Mexico": [
    { headline: "Hirving Lozano fit for opener after ankle scare", summary: "Chucky Lozano returned to full training this week, easing fears over a knock sustained in the final warm-up against Ecuador. Manager Javier Aguirre confirmed he will start against South Africa on June 11.", source: "ESPN", date: "June 9", category: "Injury" },
    { headline: "Aguirre names attacking lineup to satisfy home crowd", summary: "With the tournament opening in Mexico City, Javier Aguirre has opted for an aggressive 4-3-3 built around Santiago Giménez and Lozano. The pressure to perform in front of a home crowd is immense.", source: "BBC Sport", date: "June 8", category: "Manager" },
    { headline: "Giménez eyes Golden Boot after record Feyenoord season", summary: "Santiago Giménez scored 28 Eredivisie goals this season and arrives as Mexico's focal point. Bookmakers have him at 12/1 for the Golden Boot.", source: "The Athletic", date: "June 7", category: "Form" },
    { headline: "Azteca roars back to life for World Cup opener", summary: "Estadio Azteca will host Mexico vs South Africa in the tournament's opening match — the first WC game at the iconic venue since 1986. Over 87,000 tickets sold out within hours.", source: "Reuters", date: "June 6", category: "Preview" },
  ],
  "South Africa": [
    { headline: "Bafana Bafana arrive in Mexico City to loud reception", summary: "South Africa's squad landed to a warm welcome from the local diaspora. Coach Hugo Broos said the atmosphere reminded him of their 2010 home World Cup.", source: "BBC Sport", date: "June 9", category: "Other" },
    { headline: "Percy Tau leads South Africa's veteran attack", summary: "The Al Ahly winger, 30, is Bafana Bafana's most experienced attacking threat. Broos has built the team's counter-attacking system around Tau's pace and experience.", source: "Goal.com", date: "June 8", category: "Squad" },
    { headline: "South Africa's shock 2010 run inspires new generation", summary: "Several players in the current squad cite South Africa's group stage run on home soil as their inspiration for playing football. Broos is leaning into the underdog narrative.", source: "AP", date: "June 7", category: "Form" },
    { headline: "Broos sets defensive target: no heavy defeats", summary: "Coach Hugo Broos cautioned against expecting a deep run but set a clear goal — be competitive in all three group games and not concede more than two in any match.", source: "Reuters", date: "June 6", category: "Manager" },
  ],
  "South Korea": [
    { headline: "Son Heung-min confirmed fit, leads squad to Mexico", summary: "Tottenham captain Son, 31, overcame a minor hamstring issue to make the final squad. Korea's coach Hong Myung-bo said Son will captain the side throughout the tournament.", source: "ESPN", date: "June 9", category: "Injury" },
    { headline: "Lee Kang-in shines in final warm-up, bags brace", summary: "The PSG midfielder scored twice against Jordan in Korea's final pre-tournament friendly. His form alongside Son gives Korea a genuine attacking threat in Group A.", source: "The Athletic", date: "June 8", category: "Form" },
    { headline: "Korea eyeing round of 16 repeat from 2022", summary: "Hong Myung-bo guided the team through qualifying and has set a round of 16 as the minimum target. Korea's squad depth has improved significantly since Qatar.", source: "Goal.com", date: "June 7", category: "Preview" },
    { headline: "K-League stars push for starting spots alongside Son", summary: "Two uncapped K-League players earned surprise call-ups after standout domestic seasons. Hong said he wants to balance European experience with hungry home-based players.", source: "BBC Sport", date: "June 6", category: "Squad" },
  ],
  "Czechia": [
    { headline: "Czechia stun Denmark on penalties to reach WC for first time since 2006", summary: "Czechia defeated Denmark 3-1 on penalties in the UEFA playoff final after a 2-2 draw, booking a historic first World Cup since 2006. The nation erupted in celebration.", source: "Reuters", date: "June 2", category: "Result" },
    { headline: "Patrik Schick named captain for World Cup campaign", summary: "The Bayer Leverkusen striker, who scored 24 Bundesliga goals this season, will captain Czechia. Manager Ivan Hašek described Schick as the heartbeat of this golden generation.", source: "BBC Sport", date: "June 5", category: "Squad" },
    { headline: "Czech fans flood Mexico, Group A tickets sold out", summary: "Thousands of Czech supporters have made the journey to North America, creating an unexpected sea of red and white in Mexican stadiums.", source: "AP", date: "June 8", category: "Other" },
    { headline: "Hašek: We belong here, we will not just make up numbers", summary: "Czech manager Ivan Hašek pushed back on underdog labels, pointing to Schick's Bundesliga form and a tight defensive unit that conceded only six in qualifying.", source: "The Athletic", date: "June 7", category: "Manager" },
  ],
  "Switzerland": [
    { headline: "Granit Xhaka to lead Switzerland as tournament captain", summary: "The Bayer Leverkusen midfielder and club legend will captain Switzerland for what could be his final World Cup. Xhaka said the squad has never been more unified.", source: "BBC Sport", date: "June 9", category: "Squad" },
    { headline: "Switzerland's defensive record best in UEFA qualifying", summary: "Murat Yakin's side conceded just four goals across ten qualifying matches. Their disciplined 4-2-3-1 makes them a nightmare for any group-stage opponent.", source: "Reuters", date: "June 7", category: "Form" },
    { headline: "Breel Embolo returns to his birth country for World Cup", summary: "Born in Yaoundé, Cameroon, Embolo will play World Cup matches in the country where he was born — an emotional storyline following the Swiss striker throughout camp.", source: "The Athletic", date: "June 6", category: "Other" },
    { headline: "Yakin warns Canada and Qatar not to underestimate Switzerland", summary: "Coach Murat Yakin said Switzerland have been disrespected in pre-tournament coverage and used the perceived slight as motivation in training camp.", source: "Goal.com", date: "June 8", category: "Manager" },
  ],
  "Canada": [
    { headline: "Alphonso Davies fit and raring to go after injury scare", summary: "Bayern Munich's Davies recovered from a knee complaint in time to make the squad. Canada coach Jesse Marsch confirmed Davies will start at left back in the opening match.", source: "ESPN", date: "June 9", category: "Injury" },
    { headline: "Jonathan David leads Canada's attack with 30-goal season", summary: "David scored 30 goals for Lille this season — a Ligue 1 record for a Canadian. He arrives as one of the most in-form strikers at the entire tournament.", source: "The Athletic", date: "June 8", category: "Form" },
    { headline: "Canada set to beat their best-ever WC finish from 1986", summary: "Canada have only ever appeared in one World Cup, exiting without a point in 1986. Coach Marsch said getting out of Group B is the explicit minimum target.", source: "BBC Sport", date: "June 7", category: "Preview" },
    { headline: "Marsch under pressure after rocky qualifying road", summary: "Canada qualified as co-hosts, bypassing CONCACAF qualifying. Some pundits questioned whether Jesse Marsch's side has been tested enough ahead of tournament play.", source: "Reuters", date: "June 6", category: "Manager" },
  ],
  "Qatar": [
    { headline: "Qatar arrive as defending Asian champions", summary: "Qatar won the 2023 Asian Cup and qualified from the AFC group with ease. Coach Marquez Lopez has built a cohesive unit around the core of their 2022 home World Cup squad.", source: "Goal.com", date: "June 8", category: "Form" },
    { headline: "Akram Afif targeting improvement on 2022 group stage exit", summary: "Qatar's star midfielder scored four Asian Cup goals and is the creative engine of this team. He was the standout player in qualifying and wants to make the round of 32.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Lopez rotates squad in final warm-up ahead of Group B", summary: "Qatar rested seven starters in a 1-0 loss to Morocco in a pre-tournament friendly, suggesting Lopez is preserving legs for the group stage opener against Switzerland.", source: "Reuters", date: "June 6", category: "Manager" },
    { headline: "Qatar's 2022 experience counts for little, warns Lopez", summary: "Despite hosting 2022, Lopez said this is a fresh challenge in a tougher group. Several key 2022 players have since retired, and the squad has a new look.", source: "AP", date: "June 5", category: "Preview" },
  ],
  "Bosnia & Herzegovina": [
    { headline: "Bosnia qualify for first World Cup since 2014 via playoff drama", summary: "Bosnia beat Italy on penalties in the UEFA Path A final, ending Italy's World Cup hopes for the third straight edition. The nation celebrated one of its greatest sporting moments.", source: "BBC Sport", date: "June 1", category: "Result" },
    { headline: "Edin Džeko, 38, named in squad in emotional farewell", summary: "Bosnia's all-time top scorer will play what he confirmed is his last major tournament. Coach Sergej Barbarez included Džeko despite his age, citing his leadership value.", source: "The Athletic", date: "June 5", category: "Squad" },
    { headline: "Barbarez: Beating Italy changed everything for this generation", summary: "Bosnia's coach said the playoff win over Italy was cathartic for a nation that narrowly missed 2018 and 2022. 'This squad deserved this moment,' Barbarez said.", source: "Reuters", date: "June 6", category: "Manager" },
    { headline: "Bosnia drawn into Group B — 'the group of death' say media", summary: "Switzerland and Canada join Bosnia and Qatar in Group B. Bosnian media has labelled it the group of death for their side, but Barbarez remains upbeat.", source: "Goal.com", date: "June 4", category: "Preview" },
  ],
  "Brazil": [
    { headline: "Vinicius Jr confirmed fit after late fitness scare", summary: "Real Madrid's Vinicius Jr trained fully on Monday after missing two sessions with a thigh complaint. Brazil's medical staff cleared him ahead of the Group C opener against Scotland.", source: "ESPN", date: "June 9", category: "Injury" },
    { headline: "Rodrygo, Endrick form exciting new Brazil attack with Vini", summary: "For the first time, Brazil could field three of world football's most exciting young attackers simultaneously. Coach Dorival Junior hinted at an aggressive, fluid front three.", source: "The Athletic", date: "June 8", category: "Squad" },
    { headline: "Brazil end 24-year wait for World Cup — pressure is enormous", summary: "Brazil have not won the World Cup since 2002 and arrive with a squad many believe is their best since then. The weight of expectation is immense, say players.", source: "BBC Sport", date: "June 7", category: "Preview" },
    { headline: "Dorival Junior reshapes Brazil's midfield with added steel", summary: "Brazil's coach has deployed a double pivot that conceded just twice in the final six qualifiers. The tactical shift has drawn praise from Pele Foundation and pundits alike.", source: "Reuters", date: "June 6", category: "Form" },
  ],
  "Morocco": [
    { headline: "Achraf Hakimi set to captain Morocco after Ramos retirement", summary: "PSG fullback Hakimi will wear the armband following Ramos' international retirement. Morocco's coach Walid Regragui confirmed the appointment at a pre-tournament presser.", source: "BBC Sport", date: "June 9", category: "Squad" },
    { headline: "Regragui: 2022 was not a fluke, we come to win not just compete", summary: "Morocco's coach said the 2022 semifinal run changed the country's footballing DNA. 'We don't fear anyone,' Regragui told reporters at the team's Miami base.", source: "Reuters", date: "June 8", category: "Manager" },
    { headline: "En-Nesyri leads Morocco attack with strong Saudi Pro League form", summary: "After a prolific season for Al-Ittihad, Youssef En-Nesyri arrives in form. He has scored 22 goals since January and is Morocco's primary goal threat.", source: "The Athletic", date: "June 7", category: "Form" },
    { headline: "Morocco vs Brazil is Group C's marquee match, say analysts", summary: "With two of the world's strongest defensive teams, the Group C clash between Morocco and Brazil on June 18 is seen as the group stage's most compelling fixture.", source: "ESPN", date: "June 6", category: "Preview" },
  ],
  "Scotland": [
    { headline: "Scotland's historic first WC since 1998 — Tierney leads squad", summary: "Scotland qualified as group winners for the first time since 1998. Kieran Tierney, back from injury, is named as one of three captains alongside Robertson and McTominay.", source: "BBC Sport", date: "June 9", category: "Squad" },
    { headline: "McTominay's form for Napoli earns rave reviews ahead of WC", summary: "Scott McTominay scored 17 Serie A goals this season in a breakthrough campaign at Napoli. His engine and goals from midfield have transformed Scotland's attack.", source: "The Athletic", date: "June 8", category: "Form" },
    { headline: "Steve Clarke: We are here to surprise people", summary: "Scotland manager Steve Clarke said his side has been written off in every major competition and thrives under those circumstances. He refused to set a points target.", source: "Reuters", date: "June 7", category: "Manager" },
    { headline: "Hampden Park watch parties planned for Scotland's WC games", summary: "Over 30,000 Scottish fans will watch the Group C opener against Brazil at Hampden Park on big screens. The SFA said demand has been extraordinary.", source: "AP", date: "June 6", category: "Other" },
  ],
  "Haiti": [
    { headline: "Haiti's World Cup debut is a moment of joy for a suffering nation", summary: "Haiti qualified for their first World Cup since 1974 with a remarkable CONCACAF campaign. Players from the squad have dedicated the tournament to victims of the 2021 earthquake.", source: "AP", date: "June 8", category: "Other" },
    { headline: "Duckens Nazon leads Haiti's surprise World Cup squad", summary: "The 29-year-old striker from Ligue 2 has been in stunning form and will lead the line for Les Grenadiers. His story — playing lower-league football while representing a World Cup nation — has captivated media.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Haiti coach Rossini targets at least one point in Group C", summary: "Manager Marc Collat Rossini said reaching Brazil and Morocco would be a massive challenge, but called one point from the group a realistic and meaningful target.", source: "Reuters", date: "June 6", category: "Manager" },
    { headline: "Haiti players inspired by 1974 predecessors who scored at WC", summary: "Haiti's only previous World Cup appearance in 1974 saw Emmanuel Sanon score against Italy. The current squad have watched the footage repeatedly in camp.", source: "Goal.com", date: "June 5", category: "Preview" },
  ],
  "USA": [
    { headline: "Pulisic leading US squad with 20 Premier League goals this season", summary: "Christian Pulisic's career-best season at Chelsea has made him the undisputed leader of the US attack. Coach Mauricio Pochettino has designed the system around his movement.", source: "ESPN", date: "June 9", category: "Form" },
    { headline: "Pochettino names Gio Reyna in starting XI for Türkiye clash", summary: "After years of injury disruption, Gio Reyna is finally fit for a full tournament. Pochettino said Reyna will start in the number ten role in a high-stakes Group D opener.", source: "The Athletic", date: "June 8", category: "Squad" },
    { headline: "US faces unprecedented pressure hosting with top-tier squad", summary: "With co-hosting duties and a genuine generation of talent, this is considered the best US squad since 2002. Failure to reach the quarterfinals would be considered disappointing.", source: "Reuters", date: "June 7", category: "Preview" },
    { headline: "Pochettino: Türkiye are the best team in our group, full stop", summary: "US coach Mauricio Pochettino was unusually direct, calling Türkiye favorites in Group D. He said the opener on June 13 will define their tournament trajectory.", source: "BBC Sport", date: "June 6", category: "Manager" },
  ],
  "Australia": [
    { headline: "Mathew Ryan fit to start after shoulder concern resolved", summary: "Australia's first-choice goalkeeper trained fully on Tuesday and will start against Türkiye. Coach Tony Popovic confirmed Ryan is 100% after a scare in the warm-up camp.", source: "AP", date: "June 9", category: "Injury" },
    { headline: "Mitchell Duke leads the Socceroos line in Japan absence", summary: "With Tommy Oar retired and several strikers injured, Fagiano Okayama's Mitchell Duke has become Australia's main striker. His hold-up play is key to Popovic's 4-4-2.", source: "Goal.com", date: "June 8", category: "Squad" },
    { headline: "Popovic backs Socceroos to repeat 2022 knockouts heroics", summary: "Under Graham Arnold in 2022, Australia reached the round of 16. New coach Tony Popovic said that belief is embedded in the squad's culture and won't need to be rebuilt.", source: "BBC Sport", date: "June 7", category: "Manager" },
    { headline: "Australia's young A-League talents impress in warm-up matches", summary: "Two uncapped A-League players delivered impressive performances in friendlies against Japan and South Korea. Popovic says domestic football is producing genuinely world-ready talent.", source: "Reuters", date: "June 6", category: "Form" },
  ],
  "Türkiye": [
    { headline: "Arda Güler arrives as one of the world's hottest young talents", summary: "Real Madrid's Arda Güler has been electric in La Liga this season, with 14 goals. At 19, he's the face of Türkiye's most talented squad in a generation.", source: "ESPN", date: "June 9", category: "Form" },
    { headline: "Hakan Çalhanoğlu to sit deeper to free Güler in attack", summary: "Türkiye's setup will see Inter's Çalhanoğlu play as a deep-lying playmaker, allowing Güler to operate freely. Coach Vincenzo Montella called it the tactical key to the tournament.", source: "The Athletic", date: "June 8", category: "Manager" },
    { headline: "Türkiye's Euro 2024 quarter-final run builds World Cup belief", summary: "Türkiye reached the Euro 2024 last eight, beating Austria and pushing the Netherlands hard. That tournament hardened the squad and grew belief ahead of this campaign.", source: "BBC Sport", date: "June 7", category: "Preview" },
    { headline: "Cenk Tosun retires, Yilmaz leads the line for veteran presence", summary: "Burak Yilmaz, 38, has been included as backup striker for his leadership despite reduced playing time. Montella said his experience in big matches is irreplaceable.", source: "Reuters", date: "June 6", category: "Squad" },
  ],
  "Paraguay": [
    { headline: "Paraguay sneak into WC as 6th-place finishers after play-off win", summary: "Paraguay secured their spot via the CONMEBOL play-off system after a tense campaign. It's their first World Cup since 2010 when they reached the quarterfinals.", source: "Reuters", date: "June 5", category: "Result" },
    { headline: "Miguel Almirón named captain for World Cup return", summary: "Newcastle's experienced midfielder will captain Paraguay, providing Premier League quality to the squad. Coach Daniel Garnero said Almirón's leadership is 'irreplaceable'.", source: "BBC Sport", date: "June 8", category: "Squad" },
    { headline: "Garnero sets up Paraguay to be hard to beat against USA", summary: "Paraguay will play a compact 5-4-1 designed to frustrate opponents. Garnero said they beat Argentina twice in qualifying by keeping it tight, and the same approach applies here.", source: "Goal.com", date: "June 7", category: "Manager" },
    { headline: "Paraguay's 2010 quarter-final heroes invited to training camp", summary: "Several members of Paraguay's famous 2010 squad visited the team's New York training base to inspire the current generation ahead of their first World Cup since that run.", source: "AP", date: "June 6", category: "Other" },
  ],
  "Germany": [
    { headline: "Florian Wirtz named in starting XI for Group E opener", summary: "Bayer Leverkusen's Florian Wirtz, 21, is fully fit and will start against Ecuador. Julian Nagelsmann called him the most technically gifted German since Özil.", source: "ESPN", date: "June 9", category: "Squad" },
    { headline: "Nagelsmann backs Germany to go 'all the way' on home continent", summary: "Germany's coach rejected the notion of modest targets. 'This squad is good enough to win the tournament,' Nagelsmann said at the pre-match press conference.", source: "The Athletic", date: "June 8", category: "Manager" },
    { headline: "Müller officially retires from international football after WC squad snub", summary: "Thomas Müller confirmed his international retirement after failing to make the final 26-man squad. He thanked fans but said it was time for the next generation to shine.", source: "Reuters", date: "June 3", category: "Transfer" },
    { headline: "Germany's Bundesliga form delivers best qualifying record in Europe", summary: "Germany won nine of ten European qualifiers, conceding just three goals. The rebuilt defensive structure under Nagelsmann has transformed their reliability.", source: "BBC Sport", date: "June 6", category: "Form" },
  ],
  "Ecuador": [
    { headline: "Gonzalo Plata fit after surgery scare, named in final squad", summary: "Valladolid winger Plata recovered from a knee procedure to make Ecuador's 26-man squad. His directness and energy make him a key figure in Felix Sanchez's system.", source: "Goal.com", date: "June 8", category: "Injury" },
    { headline: "Ecuador's defensive core led by Piero Hincapié and Robert Arboleda", summary: "Bayer Leverkusen's Hincapié has developed into one of South America's best defenders. Alongside Arboleda, Ecuador have a center-back pairing that will test Germany.", source: "Reuters", date: "June 7", category: "Squad" },
    { headline: "Sanchez targets Ecuador's best World Cup finish since 2006", summary: "Ecuador reached the round of 16 in 2006. Coach Felix Sanchez said matching or bettering that in 2026 is a genuine possibility with this talented squad.", source: "BBC Sport", date: "June 6", category: "Preview" },
    { headline: "Kendry Paez emerges as Ecuador's teenage wildcard", summary: "The 17-year-old Atalanta midfielder earned a late call-up after dazzling in Serie A. At the youngest player in the squad, expectations are carefully managed — but the talent is undeniable.", source: "The Athletic", date: "June 5", category: "Form" },
  ],
  "Ivory Coast": [
    { headline: "Sébastien Haller back from cancer recovery and named in squad", summary: "Borussia Dortmund's Haller, who overcame testicular cancer in 2022, is fit and has scored 16 Bundesliga goals this season. His inclusion is one of the tournament's great sporting stories.", source: "BBC Sport", date: "June 9", category: "Squad" },
    { headline: "Ivory Coast target Group E upset against Germany in opener", summary: "Coach Emerse Faé is not cowed by the prospect of facing Germany in the first match. 'We have the quality to win that game,' he told reporters in Chicago.", source: "Reuters", date: "June 8", category: "Preview" },
    { headline: "Franck Kessié returns to national team after two-year exile", summary: "The Al-Qadsiah midfielder patched up differences with the FECAFOOT federation and was recalled to the squad. His physical midfield presence adds an important dimension.", source: "Goal.com", date: "June 7", category: "Transfer" },
    { headline: "Faé builds on 2023 AFCON title with same defensive system", summary: "Ivory Coast won the 2023 Africa Cup of Nations under Faé using an ultra-compact 4-1-4-1. He has retained the same shape for the World Cup, and it showed in qualifying.", source: "The Athletic", date: "June 6", category: "Form" },
  ],
  "Curaçao": [
    { headline: "Curaçao make history as smallest nation to reach a World Cup", summary: "The Caribbean island of 150,000 people qualified via CONCACAF, making history as the smallest-ever World Cup participant by population and land area.", source: "AP", date: "June 6", category: "Other" },
    { headline: "Leandro Bacuna leads Curaçao as experienced captain", summary: "The 34-year-old, formerly of Aston Villa and Cardiff, captains a squad that blends European-based professionals with Caribbean football culture.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Coach Remko Bicentini targets at least one goal against Germany", summary: "Curaçao's coach set a modest but meaningful target — scoring at least once in their Group E matches. 'Every goal will be celebrated like a win,' Bicentini said.", source: "Reuters", date: "June 8", category: "Manager" },
    { headline: "Curaçao's whole island stops for World Cup opener", summary: "All schools and government offices in Curaçao will close on the day of the team's first World Cup match. A national holiday has been declared for the occasion.", source: "Goal.com", date: "June 9", category: "Other" },
  ],
  "Netherlands": [
    { headline: "Cody Gakpo in best form of his career ahead of World Cup", summary: "Liverpool's Gakpo has scored 22 Premier League goals this season. Netherlands coach Ronald Koeman has him as the central figure in an all-out attacking system.", source: "ESPN", date: "June 9", category: "Form" },
    { headline: "Virgil van Dijk leads Dutch defence as captain and organiser", summary: "At 34, Van Dijk remains the cornerstone of the Netherlands' back line. Koeman said Van Dijk's reading of the game is better than ever, despite his advancing years.", source: "BBC Sport", date: "June 8", category: "Squad" },
    { headline: "Koeman sees no reason why Netherlands can't win this tournament", summary: "Netherlands' coach pushed back on suggestions that France and England are ahead of them. 'We have beaten everyone at some point. I see no favourites, just opponents,' Koeman said.", source: "The Athletic", date: "June 7", category: "Manager" },
    { headline: "Xavi Simons injury clouds Dutch preparations ahead of opener", summary: "PSG's Xavi Simons missed two training sessions with a hip flexor complaint. Koeman said he is day-to-day but will not be rushed back for the Japan opener.", source: "Reuters", date: "June 8", category: "Injury" },
  ],
  "Japan": [
    { headline: "Takefusa Kubo leads Japan's wave of La Liga talent into WC", summary: "Real Sociedad's Kubo arrives as Japan's most creative player after a stunning Liga season. He will operate as the number ten behind Minamino in Japan's 4-3-3.", source: "ESPN", date: "June 9", category: "Squad" },
    { headline: "Japan reach round of 16 in last four World Cups — trend continues?", summary: "Japan have reached the knockout stage in 2002, 2010, 2018, and 2022. Coach Hajime Moriyasu said the expectation is now for that trend to continue in 2026.", source: "The Athletic", date: "June 8", category: "Preview" },
    { headline: "Moriyasu rests entire starting XI in final pre-tournament friendly", summary: "Japan's coach used a second-string side in a 0-0 draw with Uruguay to preserve legs. All first-team players are fit for the Netherlands opener on June 14.", source: "Reuters", date: "June 6", category: "Manager" },
    { headline: "Ritsu Doan returns from Freiburg after best-ever Bundesliga season", summary: "Doan scored 13 goals and made 9 assists — career bests — and arrives in magnificent form. His partnership with Kubo is Japan's most dangerous attacking combination.", source: "Goal.com", date: "June 7", category: "Form" },
  ],
  "Sweden": [
    { headline: "Dejan Kulusevski leads Sweden into first World Cup since 2018", summary: "Tottenham's Kulusevski will captain Sweden after qualifying via UEFA playoff. It's Sweden's first World Cup since their third-place finish in Russia, and expectations are high.", source: "BBC Sport", date: "June 9", category: "Squad" },
    { headline: "Zlatan era over — Sweden's young core steps into spotlight", summary: "Sweden's post-Ibrahimovic generation has finally arrived at a World Cup. Coach Jon Dahl Tomasson has built around players under 27, with Kulusevski and Isak as the stars.", source: "The Athletic", date: "June 8", category: "Other" },
    { headline: "Alexander Isak targeting Golden Boot after Premier League season", summary: "Newcastle's Isak scored 28 Premier League goals, second only to Haaland. Sweden's system is designed to supply him, and Tomasson said Isak can win the Golden Boot.", source: "ESPN", date: "June 7", category: "Form" },
    { headline: "Tomasson: Netherlands and Japan are tough, but Sweden fear no one", summary: "Sweden's coach, a former World Cup finalist himself, said his squad has the quality to upset both Netherlands and Japan if they play their best football.", source: "Reuters", date: "June 6", category: "Manager" },
  ],
  "Tunisia": [
    { headline: "Tunisia's World Cup experience gives them edge in Group F", summary: "This is Tunisia's sixth World Cup appearance. Coach Jalel Kadri has retained the defensive shape that kept them competitive in Qatar 2022, where they beat France.", source: "Goal.com", date: "June 8", category: "Preview" },
    { headline: "Wahbi Khazri retirement leaves Tunisia without creative leader", summary: "The veteran attacking midfielder retired from international football in January. Tunisia have struggled to replace his creativity, and Kadri has had to reshape the attack.", source: "BBC Sport", date: "June 7", category: "Transfer" },
    { headline: "Youssef Msakni named squad captain in emotional send-off", summary: "The 34-year-old, playing in his third World Cup, was named permanent captain. Kadri said Msakni's experience of World Cup atmospheres is worth ten training sessions.", source: "Reuters", date: "June 6", category: "Squad" },
    { headline: "Kadri targets Tunisia's first knockout stage since 1978", summary: "Tunisia reached the knockout phase just once — in 1978. Kadri said beating Japan or Sweden is a realistic ambition with this disciplined defensive unit.", source: "The Athletic", date: "June 5", category: "Manager" },
  ],
  "Belgium": [
    { headline: "Lois Openda leads Belgium's new generation into World Cup", summary: "RB Leipzig's Openda, 24, has displaced Lukaku as Belgium's first-choice striker after an incredible Bundesliga season. Coach Domenico Tedesco calls him 'unstoppable in transition'.", source: "ESPN", date: "June 9", category: "Squad" },
    { headline: "Lukaku benched — Belgium's golden generation finally fades", summary: "Romelu Lukaku, once untouchable, has been named as a substitute for Belgium's opener against Iran. It marks the end of an era for Belgian football.", source: "The Athletic", date: "June 8", category: "Other" },
    { headline: "Kevin De Bruyne confirms this is his final international tournament", summary: "Manchester City's De Bruyne, 34, announced before departure that he will retire from international football after this World Cup. Belgium's fans are desperate for a send-off win.", source: "BBC Sport", date: "June 7", category: "Transfer" },
    { headline: "Tedesco shifts Belgium to high-press 4-3-3 ahead of Group G", summary: "Belgium's coach has abandoned the classic 3-4-3 used by predecessors and switched to an aggressive pressing system. Early results in friendlies have been impressive.", source: "Reuters", date: "June 6", category: "Manager" },
  ],
  "Iran": [
    { headline: "Mehdi Taremi fit after Inter Milan surgery — confirmed for Group G", summary: "Iran's captain and star striker recovered from a procedure to make the final squad. Coach Amir Ghalenoei said Taremi playing is 'non-negotiable' if his fitness allows.", source: "BBC Sport", date: "June 9", category: "Injury" },
    { headline: "Iran defeat Uzbekistan in final warm-up, Taremi scores brace", summary: "Taremi's two goals in a 3-1 win over Uzbekistan provided the ultimate fitness confirmation. Iran looked sharp and well-organized in the friendly.", source: "Reuters", date: "June 8", category: "Result" },
    { headline: "Ghalenoei sets defensive tone for Group G campaign", summary: "Iran's coach said their primary goal is to be difficult to beat. Against Belgium and Egypt, a point from each would represent an excellent group stage.", source: "Goal.com", date: "June 7", category: "Manager" },
    { headline: "Sardar Azmoun named vice-captain alongside Taremi", summary: "Bayer Leverkusen's Azmoun brings Champions League experience to Iran's squad. His partnership with Taremi is Iran's most dangerous attacking combination in a generation.", source: "AP", date: "June 6", category: "Squad" },
  ],
  "Egypt": [
    { headline: "Mohamed Salah confirms World Cup participation after Achilles scare", summary: "Liverpool's Salah was a major doubt after a knock in May but passed a fitness test and joined the squad. Egypt's entire campaign is built around their 32-year-old captain.", source: "ESPN", date: "June 9", category: "Injury" },
    { headline: "Salah: This is my last chance at a World Cup — I will give everything", summary: "At 32, Salah acknowledged this is likely his final World Cup appearance. He said reaching the knockout stage with Egypt would be the greatest achievement of his career.", source: "The Athletic", date: "June 8", category: "Squad" },
    { headline: "Coach Hassan names attacking lineup to support Salah", summary: "Egypt manager Ihab Galal has opted for a 4-2-3-1 with Salah as the free attacking threat supported by Mostafa Mohamed. The system sacrifices defensive security for creativity.", source: "BBC Sport", date: "June 7", category: "Manager" },
    { headline: "Egypt face Belgium — the ultimate test of Salah's World Cup dream", summary: "The Group G opener between Egypt and Belgium will be one of the tournament's most watched matches. Salah vs De Bruyne is a generational clash of midfield playmakers.", source: "Reuters", date: "June 6", category: "Preview" },
  ],
  "New Zealand": [
    { headline: "New Zealand reach World Cup knockout stage in 1982 and 2010 — aiming to repeat", summary: "The All Whites have qualified for three World Cups and reached the group stage without advancing. Coach Darren Bazeley has set a round of 32 place as a realistic target for the first time.", source: "AP", date: "June 8", category: "Preview" },
    { headline: "Chris Wood leads New Zealand at his final World Cup", summary: "The veteran striker, now 32 and playing in MLS, will lead New Zealand's attack in what he confirmed will be his last World Cup campaign.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Bazeley shuffles system to cope with Belgium's quality", summary: "New Zealand will deploy a 5-4-1 defensive block against Belgium in the group opener, then look to be more expansive against Iran and Egypt.", source: "Reuters", date: "June 6", category: "Manager" },
    { headline: "New Zealand's A-League generation arrives at biggest stage", summary: "Four uncapped A-League players made the final squad, reflecting the rising quality of the domestic game. Bazeley said the pipeline from New Zealand's leagues has never been stronger.", source: "Goal.com", date: "June 5", category: "Form" },
  ],
  "Spain": [
    { headline: "Lamine Yamal named Spain's starting winger at 18 years old", summary: "Barcelona's Yamal, who turned 18 last August, will start for Spain in all group matches. Coach Luis de la Fuente called him 'the most gifted Spanish player since Iniesta'.", source: "ESPN", date: "June 9", category: "Squad" },
    { headline: "Spain enter as reigning Euro 2024 champions and favorites", summary: "Spain won Euro 2024 with a devastating young squad and arrive as joint-favorites with France. They have not lost a competitive match since March 2023.", source: "The Athletic", date: "June 8", category: "Form" },
    { headline: "Pedri and Gavi set to form spine of Spain's midfield dominance", summary: "Barcelona's midfield pair are both fully fit for the first time at a major tournament together. De la Fuente said their combination is the best midfield partnership in the world.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "De la Fuente: We defend our Euro 2024 title, and then we want more", summary: "Spain's coach said winning back-to-back major tournaments is the explicit goal. He reminded reporters that this squad is younger and better than the 2024 Euros winning team.", source: "Reuters", date: "June 6", category: "Manager" },
  ],
  "Uruguay": [
    { headline: "Darwin Núñez and Rodrigo Bentancur lead Uruguay's core squad", summary: "Liverpool's Darwin Núñez and Juventus's Bentancur form the backbone of an experienced Uruguay squad. Coach Marcelo Bielsa calls them 'the heartbeat of this generation'.", source: "ESPN", date: "June 9", category: "Squad" },
    { headline: "Bielsa's Uruguay are Group H's most dangerous dark horse", summary: "Under Bielsa's disciplined, high-pressing 3-3-3-1, Uruguay have been one of South America's best teams in qualifying. Several analysts have tipped them to upset Spain.", source: "The Athletic", date: "June 8", category: "Preview" },
    { headline: "Federico Valverde named vice-captain for World Cup campaign", summary: "Real Madrid's Valverde is one of the world's best all-round midfielders. His box-to-box energy suits Bielsa's system perfectly and he will be crucial against Spain.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Bielsa resists Saudi Arabia approach to stay with Uruguay through WC", summary: "Marcelo Bielsa rejected a reported huge offer from the Saudi Pro League to remain Uruguay manager through the World Cup. 'I finish what I start,' Bielsa said.", source: "Reuters", date: "June 4", category: "Manager" },
  ],
  "Saudi Arabia": [
    { headline: "Saudi Arabia ride 2022 Argentina upset momentum into Group H", summary: "Saudi Arabia's stunning 2022 win over Argentina is still fresh in the memory. Coach Roberto Mancini has retained several players from that squad and is targeting a repeat upset.", source: "BBC Sport", date: "June 8", category: "Preview" },
    { headline: "Mancini reshapes Saudi attack around new SPL generation", summary: "Several Saudi Pro League-based players have broken into the squad after impressive domestic seasons. Mancini has blended SPL talent with European-based experience.", source: "Goal.com", date: "June 7", category: "Squad" },
    { headline: "Salem Al-Dawsari continues as Saudi talisman ahead of Group H", summary: "Al-Hilal's Al-Dawsari, hero of the Argentina win, has been in fine domestic form. He remains the creative engine around whom Saudi Arabia's attacking play is built.", source: "Reuters", date: "June 6", category: "Form" },
    { headline: "Mancini: Spain is not Argentina, but we can be competitive", summary: "Italy's former World Cup winner cautioned against wild ambitions but said Saudi Arabia will make Spain and Uruguay work hard for their points.", source: "AP", date: "June 5", category: "Manager" },
  ],
  "Cape Verde": [
    { headline: "Cape Verde make World Cup debut — story of a tiny football nation", summary: "An archipelago of 500,000 people, Cape Verde qualified by topping their African group ahead of Cameroon. It is one of the great qualification stories in World Cup history.", source: "BBC Sport", date: "June 7", category: "Other" },
    { headline: "Ryan Mendes leads Cape Verde into the unknown at Group H", summary: "The 34-year-old winger, now at Belenenses, is Cape Verde's most experienced player. He will captain the squad in their historic debut matches against Spain, Uruguay and Saudi Arabia.", source: "Reuters", date: "June 8", category: "Squad" },
    { headline: "Cape Verde coach Bubista: We will play with joy and no fear", summary: "Coach Rui Bubista, who guided Cape Verde through their stunning qualification campaign, said the squad will embrace every moment of their first World Cup.", source: "Goal.com", date: "June 6", category: "Manager" },
    { headline: "Cameroon furious after failing to qualify — Cape Verde's triumph shocks CAF", summary: "Cameroon, a five-time African champion, failed to top their group and missed out to Cape Verde. The result sent shockwaves through African football.", source: "AP", date: "June 2", category: "Result" },
  ],
  "France": [
    { headline: "Mbappé arrives as World Cup captain and global superstar", summary: "Kylian Mbappé, now leading Real Madrid's attack, arrives as the world's best player and France's captain. He was runner-up in 2022 and is desperate to go one better in 2026.", source: "ESPN", date: "June 9", category: "Squad" },
    { headline: "France top FIFA rankings — Deschamps names strongest squad available", summary: "With no major injuries ahead of the tournament, France coach Didier Deschamps selected his most complete squad ever, featuring depth at every position.", source: "The Athletic", date: "June 8", category: "Squad" },
    { headline: "Antoine Griezmann plays his final World Cup in style, says Deschamps", summary: "Atlético Madrid's Griezmann, 35, has been confirmed in his last World Cup squad. Deschamps called his versatility and intelligence 'irreplaceable at any age'.", source: "BBC Sport", date: "June 7", category: "Transfer" },
    { headline: "Deschamps: 2022 final defeat is still our motivation — we come for revenge", summary: "France's coach said the penalty shootout loss to Argentina in Qatar still stings and that the squad has used it as fuel for three years.", source: "Reuters", date: "June 6", category: "Manager" },
  ],
  "Senegal": [
    { headline: "Sadio Mané leads Senegal as Player of the Year favourite", summary: "After a stunning season in Saudi Arabia and with two AFCON titles to his name, Mané arrives as Senegal's captain and one of the tournament's most feared attackers.", source: "ESPN", date: "June 9", category: "Form" },
    { headline: "Aliou Cissé: Senegal are not just happy to be here, we come to win", summary: "Senegal's experienced coach pushed back on underdog narratives. With a squad featuring Mané, Gueye, and Mendy, he said they are capable of reaching the semifinals.", source: "BBC Sport", date: "June 8", category: "Manager" },
    { headline: "Edouard Mendy injury scare resolved — goalkeeper fit for Group I", summary: "Senegal's first-choice keeper was a doubt after a Champions League knock. He was cleared by medical staff and will start against France on June 12.", source: "Reuters", date: "June 7", category: "Injury" },
    { headline: "Ismaïla Sarr provides pace and power alongside Mané in attack", summary: "Watford's Sarr has been in tremendous form and will partner Mané. The two have a devastating understanding that has puzzled defenders throughout qualifying.", source: "The Athletic", date: "June 6", category: "Squad" },
  ],
  "Norway": [
    { headline: "Erling Haaland ready for World Cup — his greatest challenge yet", summary: "Manchester City's Haaland scored 38 club goals this season and arrives as one of the tournament's most feared strikers. Norway have built their entire system around him.", source: "ESPN", date: "June 9", category: "Form" },
    { headline: "Haaland: Winning the World Cup with Norway would beat everything", summary: "At 25, Haaland said winning the World Cup with Norway — who have never competed at a major tournament in his lifetime — would be greater than any club achievement.", source: "The Athletic", date: "June 8", category: "Other" },
    { headline: "Martin Ødegaard leads midfield with Arsenal captain credentials", summary: "Arsenal captain Ødegaard forms arguably Europe's best midfield partnership at international level with Haaland's energy ahead of him. Coach Ståle Solbakken calls it a dream pairing.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Norway's Group I draw delights Solbakken — France is the benchmark", summary: "Norway's coach said France in Group I is the perfect test. 'If we can compete with France, we belong here. If we beat them, we announce ourselves to the world.'", source: "Reuters", date: "June 6", category: "Manager" },
  ],
  "Iraq": [
    { headline: "Iraq qualify via inter-confederation playoff — historic achievement", summary: "Iraq beat a CONMEBOL side on penalties to secure their first World Cup appearance since 1986. The 40-year wait is over for one of Asia's most passionate football nations.", source: "AP", date: "June 5", category: "Result" },
    { headline: "Amjed Attwan leads Iraq's squad into history", summary: "The Al-Zawraa striker is Iraq's all-time leading scorer. At 28, he will carry the nation's hopes in Group I against France, Senegal, and Norway.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Iraq coach Radhi targets competitive performance in every match", summary: "Srečko Katanec said Iraq won't simply concede quietly. Against Norway and Senegal especially, he believes his side can be genuinely competitive.", source: "Reuters", date: "June 6", category: "Manager" },
    { headline: "Iraqi fans travel in huge numbers after 40-year wait", summary: "Thousands of Iraqi fans have booked flights to Canada, the primary host of Group I matches. FIFA said Iraq have the largest ticket allocation take-up of any debut nation.", source: "Goal.com", date: "June 8", category: "Other" },
  ],
  "Argentina": [
    { headline: "Messi confirmed fit — confirms this is his last World Cup", summary: "Lionel Messi passed his fitness test after an Inter Miami knee concern and declared this his final World Cup. 'I want to leave as champion,' the 38-year-old said.", source: "ESPN", date: "June 9", category: "Injury" },
    { headline: "Álvarez and Fernández given freedom to shine alongside Messi", summary: "Argentina's coach Lionel Scaloni has encouraged the team's younger stars to take responsibility rather than always deferring to Messi. 'Julián and Enzo are world-class, not just Messi's support acts.'", source: "The Athletic", date: "June 8", category: "Manager" },
    { headline: "Argentina enter as defending champions — target back-to-back titles", summary: "Only Brazil (1958, 1962) have won back-to-back World Cups. Scaloni said the squad believes they can join that exclusive list and has maintained the core of the 2022 winning squad.", source: "BBC Sport", date: "June 7", category: "Preview" },
    { headline: "Rodrigo De Paul fit after hamstring strain, starts vs Austria", summary: "Atlético Madrid's De Paul returns from a three-week absence for the Group J opener. Scaloni said De Paul's energy and pressing is non-negotiable in the midfield three.", source: "Reuters", date: "June 7", category: "Injury" },
  ],
  "Austria": [
    { headline: "Marko Arnautovic retires — Austria's new generation takes over", summary: "The veteran striker announced his international retirement following Euro 2024. Coach Ralf Rangnick has embraced the transition, building around younger Bundesliga-based players.", source: "BBC Sport", date: "June 5", category: "Transfer" },
    { headline: "Konrad Laimer leads Austria's high-intensity pressing under Rangnick", summary: "Bayern's Laimer is the physical engine of Rangnick's system. His 13km average per game in qualifying made him one of UEFA's highest-tracked outfield players.", source: "The Athletic", date: "June 8", category: "Form" },
    { headline: "Rangnick: Playing Argentina in Group J focuses the mind", summary: "Austria's German coach said drawing Argentina was the 'hardest possible group draw' but also a chance to show Europe that Austria belongs among the elite.", source: "Reuters", date: "June 7", category: "Manager" },
    { headline: "Austria's Euro 2024 quarter-final run builds World Cup confidence", summary: "Austria reached the last eight of Euro 2024, beating Poland and Hungary. That deep run gave Rangnick's squad belief that they can compete with the world's best.", source: "Goal.com", date: "June 6", category: "Preview" },
  ],
  "Algeria": [
    { headline: "Riyad Mahrez confirms World Cup return for Algeria", summary: "Al-Ahli's Mahrez, 35, was included despite his age after a strong Saudi Pro League campaign. He will captain Algeria and provide crucial experience in Group J.", source: "BBC Sport", date: "June 8", category: "Squad" },
    { headline: "Djamel Belmadi targets knockout stage as Algeria's first priority", summary: "Algeria's coach said reaching the round of 32 is the realistic goal. 'Beating Jordan is essential, and being competitive against Argentina and Austria will show our level.'", source: "Reuters", date: "June 7", category: "Manager" },
    { headline: "Algeria's Mohamed Belaïli in fine form ahead of World Cup", summary: "The Panathinaikos winger has been outstanding in Greek football and will provide width and pace in Algeria's attack. He scored seven goals and added nine assists this season.", source: "Goal.com", date: "June 6", category: "Form" },
    { headline: "Algeria's World Cup return celebrated after missing 2022", summary: "Algeria failed to qualify for Qatar 2022, a bitter blow to a passionate football nation. Their 2026 qualification has been celebrated as a national redemption moment.", source: "AP", date: "June 5", category: "Other" },
  ],
  "Jordan": [
    { headline: "Jordan make history at first ever World Cup appearance", summary: "Jordan qualified via the AFC route, making their debut in what is being celebrated as the biggest moment in Jordanian football history. Crown Prince Hussein attended the final qualifier.", source: "AP", date: "June 6", category: "Other" },
    { headline: "Mousa Al-Tamari leads Jordan's first World Cup squad", summary: "The Montpellier winger is Jordan's most dangerous player. His pace and directness will test defences in Group J, though facing Argentina will be an extreme challenge.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Jordan coach Hussam Abu Hamdan: Our goal is to score in every game", summary: "The Jordanian FA coach set a humble but specific target — to score at least one goal per match and prove Jordan deserves to be at the tournament.", source: "Reuters", date: "June 8", category: "Manager" },
    { headline: "FIFA allocates Jordan bumper ticket quota — sells out in hours", summary: "Jordan's allocation for their opening match against Algeria sold out within hours of going on sale. Jordanian fans are planning a significant presence in North America.", source: "Goal.com", date: "June 5", category: "Other" },
  ],
  "Portugal": [
    { headline: "Cristiano Ronaldo named in squad — confirms this is his last WC", summary: "Now 41 and playing in Saudi Arabia, Ronaldo was included by coach Roberto Martínez and confirmed this is his World Cup farewell. Portugal's fans are divided on his inclusion.", source: "ESPN", date: "June 9", category: "Squad" },
    { headline: "Bruno Fernandes is now Portugal's actual leader, says Martínez", summary: "Manchester United's Fernandes has taken ownership of the Portugal armband in Ronaldo's absence from the starting XI. Martínez said the transition is 'complete and natural'.", source: "The Athletic", date: "June 8", category: "Manager" },
    { headline: "Rafael Leão in best form of his career ahead of Group K", summary: "AC Milan's Leão has 22 Serie A goals and 14 assists. His directness and two-footedness make him the most dangerous attacker in the Portuguese squad.", source: "BBC Sport", date: "June 7", category: "Form" },
    { headline: "Portugal targeting their first World Cup title in 2026", summary: "Portugal's golden generation has reached WC semifinals (2006) and Euro finals (2016). Coach Martínez said this squad, finally, has the depth to go all the way.", source: "Reuters", date: "June 6", category: "Preview" },
  ],
  "Colombia": [
    { headline: "Luis Díaz leads Colombia's attacking trio with explosive pace", summary: "Liverpool's Díaz arrives after a brilliant Premier League season. Alongside James Rodríguez and Falcao's successor Borré, Colombia have a front three with genuine World Cup quality.", source: "ESPN", date: "June 9", category: "Form" },
    { headline: "James Rodríguez, 34, included as creative veteran in final squad", summary: "Colombia's most technically gifted player was included despite his age following a strong club season. Coach Néstor Lorenzo said Rodríguez can still be decisive in big moments.", source: "The Athletic", date: "June 8", category: "Squad" },
    { headline: "Colombia's Copa América 2024 run inspires World Cup ambition", summary: "Colombia reached the Copa América final in 2024, losing narrowly to Argentina. Lorenzo said that run proved they can compete over a tournament.", source: "BBC Sport", date: "June 7", category: "Preview" },
    { headline: "Lorenzo builds Colombia around defensive solidity plus Díaz", summary: "Colombia conceded just six goals in qualifying. The 4-2-3-1 is built to be hard to break down while giving Díaz freedom to exploit space on the counter.", source: "Reuters", date: "June 6", category: "Manager" },
  ],
  "DR Congo": [
    { headline: "DR Congo qualify via inter-confederation playoff in landmark win", summary: "DR Congo beat a South American side on penalties in the inter-confederation playoff, sending a nation of 100 million into raptures. It's their first WC since 1974.", source: "AP", date: "June 4", category: "Result" },
    { headline: "Cédric Bakambu leads DR Congo attack after impressive campaign", summary: "The experienced striker, playing in Brazil's Serie A, scored five goals in DR Congo's playoff run. He arrives as the squad's most dangerous finisher.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "DR Congo coach Hector Cuellar targets surprise result against Portugal", summary: "The Colombian coach said DR Congo will defend deep against Portugal but look to exploit counter-attacking opportunities. 'One goal here changes everything,' he said.", source: "Reuters", date: "June 8", category: "Manager" },
    { headline: "DR Congo's historic qualification unites nation amid political tension", summary: "Football has provided a rare moment of unity in the Democratic Republic of Congo. President Tshisekedi attended the final qualifier as the country celebrated as one.", source: "Goal.com", date: "June 5", category: "Other" },
  ],
  "Uzbekistan": [
    { headline: "Uzbekistan make World Cup debut after stunning AFC campaign", summary: "Uzbekistan qualified for their first-ever World Cup after topping their AFC qualifying group. The Central Asian nation has invested heavily in youth development over the last decade.", source: "AP", date: "June 5", category: "Other" },
    { headline: "Eldor Shomurodov leads Uzbekistan into historic first World Cup", summary: "Roma's Shomurodov is Uzbekistan's best-known player in European football. The striker has matured significantly and will be their focal point against Portugal and Colombia.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Uzbekistan's entire squad based in Asian and Turkish leagues", summary: "Unlike debut sides with European-based players, Uzbekistan's squad is almost entirely from Central Asian and Turkish football. Their collective spirit is their main strength.", source: "Reuters", date: "June 6", category: "Squad" },
    { headline: "Srecko Katanec: We will be organised and hard to beat in Group K", summary: "Uzbekistan's coach said making the most of set-pieces and defending compactly is the game plan. 'We respect everyone but fear no one,' he told reporters.", source: "Goal.com", date: "June 8", category: "Manager" },
  ],
  "England": [
    { headline: "Harry Kane targets goals record at his second World Cup", summary: "Bayern's Kane arrives having scored 37 Bundesliga goals this season. At 32, he is at the peak of his powers and his goals have driven England to being joint-favorites.", source: "ESPN", date: "June 9", category: "Form" },
    { headline: "Southgate successor Thomas Tuchel names attacking squad", summary: "Germany's former coach, now in charge of England, has selected a bold, attack-minded 26-man squad. Tuchel said England have been too cautious under previous managers.", source: "The Athletic", date: "June 8", category: "Manager" },
    { headline: "Jude Bellingham fit after Champions League final knock", summary: "Real Madrid's Bellingham suffered a minor ankle issue in the Champions League final but has trained fully and will start for England in Group L.", source: "BBC Sport", date: "June 7", category: "Injury" },
    { headline: "England's 60-year wait — Tuchel says squad is good enough to end it", summary: "England have not won a major tournament since 1966. New coach Tuchel said this generation — Kane, Bellingham, Saka — is objectively the best England have had since that era.", source: "Reuters", date: "June 6", category: "Preview" },
  ],
  "Croatia": [
    { headline: "Luka Modrić, 40, named in squad for what he calls his last tournament", summary: "Real Madrid legend Modrić is included in Croatia's squad in what all parties agree will be his final international tournament. The farewell narrative is inescapable.", source: "ESPN", date: "June 9", category: "Squad" },
    { headline: "Modrić: This squad can reach the semi-finals without me in every game", summary: "Croatia's captain said younger players like Kovačić and Gvardiol have matured enough to carry the team. He will be managed carefully throughout the group stage.", source: "The Athletic", date: "June 8", category: "Manager" },
    { headline: "Joško Gvardiol leads Croatia's defence in World Cup prime", summary: "Manchester City's Gvardiol, 22, is considered one of the world's best centre-backs. His partnership with Šutalo gives Croatia a commanding defensive foundation.", source: "BBC Sport", date: "June 7", category: "Form" },
    { headline: "Croatia reach WC knockouts in every tournament since 2014 — streak continues?", summary: "Croatia have reached the knockouts in 2014, 2018 (final), and 2022 (third place). Coach Zlatko Dalić said the expectation is the same — minimum round of 16.", source: "Reuters", date: "June 6", category: "Preview" },
  ],
  "Panama": [
    { headline: "Panama return to World Cup with vastly improved squad since 2018", summary: "Panama made their debut in 2018 and went out at the group stage. Eight years on, coach Thomas Christiansen has assembled a more experienced and tactically mature squad.", source: "AP", date: "June 8", category: "Preview" },
    { headline: "Ismael Díaz emerges as Panama's key creative threat", summary: "The 23-year-old Almería winger has broken into the first team and is Panama's most exciting attacker. He scored three goals in CONCACAF qualifying to cement his place.", source: "BBC Sport", date: "June 7", category: "Form" },
    { headline: "Christiansen: England and Croatia are top quality, but Panama won't be passive", summary: "Panama's coach said his side will not sit back and absorb pressure. 'We will press and create chances. We respect our opponents, we won't be afraid of them.'", source: "Reuters", date: "June 6", category: "Manager" },
    { headline: "Panama's qualification celebrated as national holiday in Panama City", summary: "Schools and government offices closed on the day of Panama's final qualifier. Football is increasingly central to Panamanian national identity.", source: "Goal.com", date: "June 5", category: "Other" },
  ],
  "Ghana": [
    { headline: "Mohammed Kudus leads Ghana's attacking press into Group L", summary: "West Ham's Kudus has been electric in the Premier League, scoring 17 goals. Ghana's coach Otto Addo has built the system to give Kudus maximum freedom to create and score.", source: "ESPN", date: "June 9", category: "Form" },
    { headline: "Ghana eyeing round of 16 return after 2010 quarter-final heroics", summary: "Ghana came agonisingly close to the semi-finals in 2010. Addo said this squad has the quality to match that run if the team is at their best.", source: "The Athletic", date: "June 8", category: "Preview" },
    { headline: "Andre Ayew bows out: final call-up for Ghana veteran", summary: "Andre Ayew, 34, received a farewell call-up in recognition of his contribution to Ghanaian football. He provides experience behind Kudus and Thomas Partey.", source: "BBC Sport", date: "June 7", category: "Squad" },
    { headline: "Thomas Partey fit after Arsenal's Champions League campaign", summary: "Ghana's midfield anchor returned to training after an intense club season. Addo confirmed Partey is fully fit and will start in the Group L opener against Panama.", source: "Reuters", date: "June 6", category: "Injury" },
    { headline: "Ghana delegation clears CBP — State Dept fast-track visa program utilized", summary: "Ghanaian nationals require non-immigrant visas. The US Embassy in Accra processed the squad's B-1 applications under the FIFA-State Department World Cup coordination channel. All cleared at Atlanta.", source: "AP", date: "June 7", category: "Entry" },
  ],
};

// ── INJECT ENTRY STORIES ── prepend to each team's news array
const ENTRY_STORIES = {
  "Mexico": { headline: "Mexico players enter as co-hosts — CBP fast-track lanes activated", summary: "As a co-host nation, Mexico's players and staff received expedited CBP processing at all US ports of entry. State Department confirmed World Cup accreditation cards function as visa equivalents for tournament travel.", source: "Reuters", date: "June 8", category: "Entry" },
  "South Africa": { headline: "South Africa squad clears US entry — no visa issues reported", summary: "All 26 South Africa players and staff cleared CBP processing without incident at Dallas/Fort Worth. State Department's FIFA-coordinated visa program covered the entire delegation.", source: "AP", date: "June 8", category: "Entry" },
  "South Korea": { headline: "South Korea delegation enters US under ESTA — no complications", summary: "South Korea is a Visa Waiver Program participant, so all squad members entered on ESTA authorization. CBP processed the team at LAX within 45 minutes under the World Cup delegation lane.", source: "AP", date: "June 8", category: "Entry" },
  "Czechia": { headline: "Czech squad uses Visa Waiver Program — smooth CBP entry", summary: "As an EU member and VWP country, Czechia's players entered on ESTA. CBP confirmed the team cleared processing at JFK in under an hour using dedicated World Cup lanes.", source: "Reuters", date: "June 8", category: "Entry" },
  "Switzerland": { headline: "Switzerland enters US seamlessly via Visa Waiver Program", summary: "Swiss players and staff held valid ESTA authorizations and cleared CBP processing at Newark without delay. State Department's World Cup coordination office confirmed zero complications.", source: "AP", date: "June 7", category: "Entry" },
  "Canada": { headline: "Canada players enter as co-hosts — CBP pre-clearance used", summary: "Canadian players used existing CBP pre-clearance facilities at Toronto Pearson and Vancouver airports. As a co-host, Canada's delegation received expedited processing equivalent to Mexico and the US.", source: "Reuters", date: "June 7", category: "Entry" },
  "Qatar": { headline: "Qatar squad clears CBP — B-1 visas issued after standard review", summary: "Qatar's delegation received B-1 visas after a routine State Department review process. CBP confirmed all 26 players and staff cleared inspection at Houston's George Bush Intercontinental Airport.", source: "AP", date: "June 7", category: "Entry" },
  "Bosnia & Herzegovina": { headline: "Bosnia delegation clears US entry after visa processing delay", summary: "Several Bosnia staff members experienced a brief delay when their B-1 visas required additional State Department review. All cleared CBP inspection within 48 hours and the squad is confirmed in the US.", source: "Reuters", date: "June 7", category: "Entry" },
  "Brazil": { headline: "Brazil squad requires B-1 visas — all 26 clear CBP at Miami", summary: "Brazilian citizens require non-immigrant visas for US entry. FIFA worked with State Department to expedite the delegation's B-1 issuance. CBP confirmed all cleared at Miami International.", source: "AP", date: "June 8", category: "Entry" },
  "Morocco": { headline: "Morocco squad clears CBP after secondary screening at JFK", summary: "Several Morocco players underwent secondary CBP inspection at JFK, consistent with standard protocols for nationals of certain countries. All cleared within hours and the squad is confirmed present.", source: "Reuters", date: "June 8", category: "Entry" },
  "Scotland": { headline: "Scotland enters on UK passports — VWP clears team at Boston", summary: "Scotland's players, traveling on UK passports, qualified for ESTA/Visa Waiver Program entry. The squad cleared CBP at Boston Logan in under an hour using World Cup delegation processing.", source: "AP", date: "June 7", category: "Entry" },
  "Haiti": { headline: "Haiti delegation clears US entry after extended 24-hour review", summary: "Haiti is among countries subject to heightened CBP scrutiny, and several squad members required additional documentation review. State Department confirmed all 26 cleared entry after a 24-hour process.", source: "Reuters", date: "June 7", category: "Entry" },
  "USA": { headline: "US squad trains at home — CBP focused on inbound delegations", summary: "As the host nation, the US squad requires no entry processing. CBP's World Cup coordination unit is managing inbound delegations, with US Soccer working directly with DHS on tournament logistics.", source: "AP", date: "June 8", category: "Entry" },
  "Australia": { headline: "Australia clears CBP at LAX — VWP processing complete", summary: "Australia is a Visa Waiver Program country. All Australian squad members entered on ESTA authorization and cleared CBP at Los Angeles without issue.", source: "AP", date: "June 7", category: "Entry" },
  "Türkiye": { headline: "Turkey squad requires B-1 visas — State Dept expedites WC delegation", summary: "Turkish citizens require non-immigrant visas for US entry. State Department's FIFA coordination channel processed the delegation's B-1 applications within five days. All cleared CBP at New York.", source: "Reuters", date: "June 7", category: "Entry" },
  "Paraguay": { headline: "Paraguay delegation clears US entry — B-1 visas processed in Asunción", summary: "Paraguay's players obtained B-1 visas at the US Embassy in Asunción under a FIFA-State Department expedited program. CBP confirmed clearance at Miami International Airport.", source: "AP", date: "June 7", category: "Entry" },
  "Germany": { headline: "Germany squad enters on VWP — zero complications at CBP", summary: "German nationals qualify for ESTA/Visa Waiver Program entry. The squad cleared CBP at Dallas/Fort Worth in under 40 minutes using dedicated World Cup lanes.", source: "AP", date: "June 8", category: "Entry" },
  "Ecuador": { headline: "Ecuador squad requires B-1 visas — all clear CBP at Houston", summary: "Ecuador's players obtained B-1 visas via expedited State Department processing. CBP confirmed the full squad cleared at George Bush Intercontinental Airport without incident.", source: "Reuters", date: "June 7", category: "Entry" },
  "Ivory Coast": { headline: "Ivory Coast delegation cleared CBP after standard visa review", summary: "All Ivory Coast players and staff held valid B-1 visas issued through the US Embassy in Abidjan. CBP processed the delegation at Atlanta Hartsfield-Jackson under the World Cup fast-track program.", source: "AP", date: "June 7", category: "Entry" },
  "Curaçao": { headline: "Curaçao enters on Dutch passports — VWP eases most of squad", summary: "Curaçao players holding Dutch passports qualified for ESTA/VWP entry. Some locally-born players with only Netherlands Antilles documentation required B-1 visas, which were processed without issue.", source: "Reuters", date: "June 7", category: "Entry" },
  "Netherlands": { headline: "Netherlands squad clears CBP — VWP entry at Newark", summary: "Dutch nationals qualify for ESTA authorization. The full squad cleared CBP at Newark Liberty in under 45 minutes. State Department confirmed no issues with the delegation.", source: "AP", date: "June 8", category: "Entry" },
  "Japan": { headline: "Japan squad enters on VWP — CBP clears team at LAX quickly", summary: "Japan is a Visa Waiver Program country. All squad members cleared ESTA-based CBP processing at Los Angeles International Airport within an hour of landing.", source: "AP", date: "June 7", category: "Entry" },
  "Sweden": { headline: "Sweden enters under VWP — no CBP complications reported", summary: "Swedish nationals qualify for ESTA/Visa Waiver Program entry. The squad processed through CBP at Chicago O'Hare without delay under the World Cup delegation fast-track lane.", source: "Reuters", date: "June 7", category: "Entry" },
  "Tunisia": { headline: "Tunisia squad requires B-1 visas — two players flag extra CBP screening", summary: "Tunisian nationals require non-immigrant visas and two players underwent enhanced CBP secondary inspection. Both were cleared after document review, and the full squad is confirmed in the US.", source: "Reuters", date: "June 7", category: "Entry" },
  "Belgium": { headline: "Belgium squad enters on VWP — Schengen passport processing smooth", summary: "Belgian players cleared CBP at Atlanta Hartsfield using ESTA authorization. State Department confirmed no complications with the Belgian delegation's entry documentation.", source: "AP", date: "June 8", category: "Entry" },
  "Iran": { headline: "Iran squad faces heightened CBP scrutiny — all cleared after 72-hour review", summary: "Iranian nationals face heightened US entry scrutiny due to existing travel restrictions. State Department issued special World Cup visas after extensive national security review. All players cleared CBP, though the process took 72 hours longer than most delegations.", source: "Reuters", date: "June 6", category: "Entry" },
  "Egypt": { headline: "Egypt squad clears CBP — B-1 visas issued in Cairo", summary: "Egypt's delegation received B-1 visas through the US Embassy Cairo's expedited FIFA program. CBP processed the team at Miami International without complications.", source: "AP", date: "June 7", category: "Entry" },
  "New Zealand": { headline: "New Zealand enters on VWP — CBP fast-track at LAX", summary: "New Zealand is a Visa Waiver Program participant. All squad members cleared ESTA-based processing at Los Angeles International Airport without complications.", source: "AP", date: "June 7", category: "Entry" },
  "Spain": { headline: "Spain squad clears CBP via VWP — no complications at entry", summary: "Spanish nationals qualify for ESTA/Visa Waiver Program entry. The squad cleared CBP at Miami International in under 45 minutes using dedicated World Cup delegation processing lanes.", source: "AP", date: "June 8", category: "Entry" },
  "Uruguay": { headline: "Uruguay requires B-1 visas — all 26 players clear CBP at Miami", summary: "Uruguayan citizens require non-immigrant visas for US entry. State Department's World Cup expedited processing issued all B-1 visas within five days. CBP cleared the squad at Miami.", source: "Reuters", date: "June 7", category: "Entry" },
  "Saudi Arabia": { headline: "Saudi squad clears CBP — B-1 visas processed via FIFA-State Dept channel", summary: "Saudi nationals require non-immigrant visas. State Department's FIFA coordination program processed the delegation's B-1 applications, and CBP cleared the team at Dallas without incident.", source: "AP", date: "June 7", category: "Entry" },
  "Cape Verde": { headline: "Cape Verde delegation clears US entry with B-1 visas", summary: "Cape Verdean nationals require visas for US entry. The US Embassy in Praia processed the squad's B-1 visas under an expedited FIFA program. CBP cleared the full delegation at Boston Logan.", source: "Reuters", date: "June 7", category: "Entry" },
  "France": { headline: "France squad enters on VWP — team clears CBP at JFK in 35 minutes", summary: "French nationals qualify for ESTA/Visa Waiver Program entry. France's squad cleared CBP at John F. Kennedy International Airport using the World Cup delegation fast-track lane.", source: "AP", date: "June 8", category: "Entry" },
  "Senegal": { headline: "Senegal squad requires B-1 visas — one player held at CBP for additional review", summary: "Senegalese nationals require non-immigrant visas and one player was held for several hours of additional CBP inspection. He was subsequently cleared and joined the squad in Toronto.", source: "Reuters", date: "June 7", category: "Entry" },
  "Norway": { headline: "Norway enters on VWP — squad clears CBP at Boston Logan", summary: "Norwegian nationals qualify for ESTA authorization. The full squad processed through CBP at Boston Logan International without complications under the World Cup delegation lane.", source: "AP", date: "June 7", category: "Entry" },
  "Iraq": { headline: "Iraq squad faces most complex US entry — all players eventually cleared", summary: "Iraqi nationals face significant US entry barriers including enhanced CBP screening and State Department national security review. All 26 players ultimately received clearance, though the process took over a week longer than most delegations.", source: "Reuters", date: "June 5", category: "Entry" },
  "Argentina": { headline: "Argentina squad requires B-1 visas — all clear CBP at Miami", summary: "Argentine nationals require non-immigrant visas. B-1 visas were issued through the US Embassy in Buenos Aires under the FIFA expedited program. CBP confirmed the full squad cleared at Miami.", source: "AP", date: "June 8", category: "Entry" },
  "Austria": { headline: "Austria enters on VWP — CBP fast-track processing at JFK", summary: "Austrian nationals qualify for ESTA/Visa Waiver Program entry. The squad cleared CBP at John F. Kennedy International without delay using the World Cup delegation processing lane.", source: "AP", date: "June 7", category: "Entry" },
  "Algeria": { headline: "Algeria squad requires B-1 visas — two staff face additional CBP review", summary: "Algerian nationals require non-immigrant visas. Two team staff members underwent extended CBP secondary inspection. Both were cleared after document verification, with no players affected.", source: "Reuters", date: "June 7", category: "Entry" },
  "Jordan": { headline: "Jordan delegation clears US entry after extended State Dept visa review", summary: "Jordanian nationals require non-immigrant visas and the delegation's B-1 applications underwent a more thorough State Department review process. All 26 players cleared CBP at Chicago, though processing took ten days.", source: "Reuters", date: "June 6", category: "Entry" },
  "Portugal": { headline: "Portugal squad enters on VWP — CBP clears team at JFK without issue", summary: "Portuguese nationals qualify for ESTA/Visa Waiver Program entry. The squad cleared CBP at John F. Kennedy International in under an hour using World Cup delegation fast-track processing.", source: "AP", date: "June 8", category: "Entry" },
  "Colombia": { headline: "Colombia squad requires B-1 visas — all cleared at Miami CBP", summary: "Colombian nationals require non-immigrant visas. The US Embassy in Bogotá processed the squad's B-1 applications under the FIFA-State Department fast-track program. All cleared at Miami.", source: "AP", date: "June 7", category: "Entry" },
  "DR Congo": { headline: "DR Congo delegation faces extended CBP processing — all players cleared after 36 hours", summary: "Congolese nationals face enhanced US entry scrutiny. Multiple squad members underwent secondary CBP inspection at Atlanta. All were cleared after document review, though processing took approximately 36 hours.", source: "Reuters", date: "June 6", category: "Entry" },
  "Uzbekistan": { headline: "Uzbekistan squad clears US entry — B-1 visas issued in Tashkent", summary: "Uzbek nationals require non-immigrant visas. The US Embassy in Tashkent processed the delegation under the FIFA expedited program. CBP confirmed the full squad cleared at Dallas without complications.", source: "AP", date: "June 7", category: "Entry" },
  "England": { headline: "England squad enters on UK passports — VWP clears team at Newark", summary: "English players, traveling on UK passports, qualified for ESTA/Visa Waiver Program entry. The squad cleared CBP at Newark Liberty International in under 40 minutes using World Cup delegation lanes.", source: "AP", date: "June 8", category: "Entry" },
  "Croatia": { headline: "Croatia enters on VWP — EU passport holders clear CBP at JFK", summary: "Croatian nationals qualify for ESTA/Visa Waiver Program entry as EU passport holders. The squad cleared CBP at John F. Kennedy International without delay.", source: "AP", date: "June 7", category: "Entry" },
  "Panama": { headline: "Panama squad requires B-1 visas — all clear CBP at Miami", summary: "Panamanian nationals require non-immigrant visas for US entry. B-1 visas were processed through the US Embassy in Panama City under the FIFA expedited program. CBP cleared the full squad at Miami International.", source: "Reuters", date: "June 7", category: "Entry" },
};

// Prepend entry story to each team's news array
Object.keys(ENTRY_STORIES).forEach(team => {
  if (NEWS_DATA[team]) NEWS_DATA[team].unshift(ENTRY_STORIES[team]);
});

// Build overview — mix of notable entry issues + top football stories
const OVERVIEW_NEWS = [
  { team: "Iraq", ...ENTRY_STORIES["Iraq"] },
  { team: "Iran", ...ENTRY_STORIES["Iran"] },
  { team: "Haiti", ...ENTRY_STORIES["Haiti"] },
  { team: "Jordan", ...ENTRY_STORIES["Jordan"] },
  { team: "DR Congo", ...ENTRY_STORIES["DR Congo"] },
  { team: "Senegal", ...ENTRY_STORIES["Senegal"] },
  { team: "France", ...NEWS_DATA["France"][1] },
  { team: "Norway", ...NEWS_DATA["Norway"][1] },
  { team: "England", ...NEWS_DATA["England"][3] },
  { team: "Brazil", ...NEWS_DATA["Brazil"][1] },
  { team: "Argentina", ...NEWS_DATA["Argentina"][1] },
  { team: "Morocco", ...ENTRY_STORIES["Morocco"] },
  { team: "Tunisia", ...ENTRY_STORIES["Tunisia"] },
  { team: "Germany", ...NEWS_DATA["Germany"][1] },
];

const TEAMS = [
  { name: "Mexico",               flag: "🇲🇽", group: "A", confederation: "CONCACAF" },
  { name: "South Africa",         flag: "🇿🇦", group: "A", confederation: "CAF" },
  { name: "South Korea",          flag: "🇰🇷", group: "A", confederation: "AFC" },
  { name: "Czechia",              flag: "🇨🇿", group: "A", confederation: "UEFA" },
  { name: "Switzerland",          flag: "🇨🇭", group: "B", confederation: "UEFA" },
  { name: "Canada",               flag: "🇨🇦", group: "B", confederation: "CONCACAF" },
  { name: "Qatar",                flag: "🇶🇦", group: "B", confederation: "AFC" },
  { name: "Bosnia & Herzegovina", flag: "🇧🇦", group: "B", confederation: "UEFA" },
  { name: "Brazil",               flag: "🇧🇷", group: "C", confederation: "CONMEBOL" },
  { name: "Morocco",              flag: "🇲🇦", group: "C", confederation: "CAF" },
  { name: "Scotland",             flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", group: "C", confederation: "UEFA" },
  { name: "Haiti",                flag: "🇭🇹", group: "C", confederation: "CONCACAF" },
  { name: "USA",                  flag: "🇺🇸", group: "D", confederation: "CONCACAF" },
  { name: "Australia",            flag: "🇦🇺", group: "D", confederation: "AFC" },
  { name: "Türkiye",              flag: "🇹🇷", group: "D", confederation: "UEFA" },
  { name: "Paraguay",             flag: "🇵🇾", group: "D", confederation: "CONMEBOL" },
  { name: "Germany",              flag: "🇩🇪", group: "E", confederation: "UEFA" },
  { name: "Ecuador",              flag: "🇪🇨", group: "E", confederation: "CONMEBOL" },
  { name: "Ivory Coast",          flag: "🇨🇮", group: "E", confederation: "CAF" },
  { name: "Curaçao",              flag: "🇨🇼", group: "E", confederation: "CONCACAF" },
  { name: "Netherlands",          flag: "🇳🇱", group: "F", confederation: "UEFA" },
  { name: "Japan",                flag: "🇯🇵", group: "F", confederation: "AFC" },
  { name: "Sweden",               flag: "🇸🇪", group: "F", confederation: "UEFA" },
  { name: "Tunisia",              flag: "🇹🇳", group: "F", confederation: "CAF" },
  { name: "Belgium",              flag: "🇧🇪", group: "G", confederation: "UEFA" },
  { name: "Iran",                 flag: "🇮🇷", group: "G", confederation: "AFC" },
  { name: "Egypt",                flag: "🇪🇬", group: "G", confederation: "CAF" },
  { name: "New Zealand",          flag: "🇳🇿", group: "G", confederation: "OFC" },
  { name: "Spain",                flag: "🇪🇸", group: "H", confederation: "UEFA" },
  { name: "Uruguay",              flag: "🇺🇾", group: "H", confederation: "CONMEBOL" },
  { name: "Saudi Arabia",         flag: "🇸🇦", group: "H", confederation: "AFC" },
  { name: "Cape Verde",           flag: "🇨🇻", group: "H", confederation: "CAF" },
  { name: "France",               flag: "🇫🇷", group: "I", confederation: "UEFA" },
  { name: "Senegal",              flag: "🇸🇳", group: "I", confederation: "CAF" },
  { name: "Norway",               flag: "🇳🇴", group: "I", confederation: "UEFA" },
  { name: "Iraq",                 flag: "🇮🇶", group: "I", confederation: "AFC" },
  { name: "Argentina",            flag: "🇦🇷", group: "J", confederation: "CONMEBOL" },
  { name: "Austria",              flag: "🇦🇹", group: "J", confederation: "UEFA" },
  { name: "Algeria",              flag: "🇩🇿", group: "J", confederation: "CAF" },
  { name: "Jordan",               flag: "🇯🇴", group: "J", confederation: "AFC" },
  { name: "Portugal",             flag: "🇵🇹", group: "K", confederation: "UEFA" },
  { name: "Colombia",             flag: "🇨🇴", group: "K", confederation: "CONMEBOL" },
  { name: "DR Congo",             flag: "🇨🇩", group: "K", confederation: "CAF" },
  { name: "Uzbekistan",           flag: "🇺🇿", group: "K", confederation: "AFC" },
  { name: "England",              flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "L", confederation: "UEFA" },
  { name: "Croatia",              flag: "🇭🇷", group: "L", confederation: "UEFA" },
  { name: "Panama",               flag: "🇵🇦", group: "L", confederation: "CONCACAF" },
  { name: "Ghana",                flag: "🇬🇭", group: "L", confederation: "CAF" },
];


export { NEWS_DATA, OVERVIEW_NEWS, TEAMS };
